import OpenAI from 'openai';
import type { ChatCompletionMessageParam } from 'openai/resources/chat/completions';
import type { AdvancedSettings } from '@ai-retouch/shared';
import { resolveImageUrlsFromText } from './image-url-resolver.js';
import type {
  AdapterRequest,
  AdapterResponse,
  AdapterResultImage,
  AdapterStreamCallbacks,
  ResolvedProvider,
} from './types.js';

// ─── Client & helpers ─────────────────────────────────

function createClient(provider: ResolvedProvider): OpenAI {
  const baseURL =
    provider.urlMode === 'full'
      ? provider.baseUrl.replace(/\/+$/, '')
      : `${provider.baseUrl.replace(/\/+$/, '')}/v1`;

  if (provider.useAuthorizationFormat) {
    return new OpenAI({
      baseURL,
      apiKey: 'placeholder',
      defaultHeaders: { 'x-api-key': provider.apiKey },
    });
  }
  return new OpenAI({ baseURL, apiKey: provider.apiKey });
}

function buildParams(settings: AdvancedSettings): Record<string, unknown> {
  const params: Record<string, unknown> = {};
  if (settings.temperature?.enabled) params.temperature = settings.temperature.value;
  if (settings.maxOutputTokens?.enabled) params.max_tokens = settings.maxOutputTokens.value;
  if (settings.topP?.enabled) params.top_p = settings.topP.value;
  if (settings.thinking?.reasoningEffort?.enabled)
    params.reasoning_effort = settings.thinking.reasoningEffort.value;
  return params;
}

function buildMessages(
  request: AdapterRequest,
  strategy: ResolvedProvider['imageHistoryStrategy'],
): ChatCompletionMessageParam[] {
  const messages: ChatCompletionMessageParam[] = [];

  if (request.history?.length) {
    let pendingAssistantImages: AdapterRequest['images'] = [];

    for (const turn of request.history) {
      if (turn.role === 'user') {
        const parts: OpenAI.Chat.Completions.ChatCompletionContentPart[] = [];

        if (strategy === 'attach_to_user' && pendingAssistantImages.length > 0) {
          for (const img of pendingAssistantImages) {
            parts.push({
              type: 'image_url' as const,
              image_url: { url: `data:${img.mimeType};base64,${img.data}` },
            });
          }
          const n = pendingAssistantImages.length;
          parts.push({
            type: 'text',
            text: `[The preceding ${n} image(s) are the result(s) generated by AI in the previous response]\n\n${turn.content}`,
          });
          pendingAssistantImages = [];
        } else {
          if (turn.images?.length) {
            for (const img of turn.images) {
              parts.push({
                type: 'image_url' as const,
                image_url: { url: `data:${img.mimeType};base64,${img.data}` },
              });
            }
          }
          parts.push({ type: 'text', text: turn.content });
        }

        messages.push({ role: 'user', content: parts });
      } else {
        if (turn.images?.length) {
          if (strategy === 'embed_in_assistant') {
            const parts: OpenAI.Chat.Completions.ChatCompletionContentPart[] = turn.images.map(
              (img) => ({
                type: 'image_url' as const,
                image_url: { url: `data:${img.mimeType};base64,${img.data}` },
              }),
            );
            parts.push({ type: 'text', text: turn.content });
            messages.push({ role: 'assistant', content: parts as any });
          } else {
            pendingAssistantImages = turn.images;
            messages.push({ role: 'assistant', content: turn.content });
          }
        } else {
          messages.push({ role: 'assistant', content: turn.content });
        }
      }
    }

    if (strategy === 'attach_to_user' && pendingAssistantImages.length > 0) {
      const parts: OpenAI.Chat.Completions.ChatCompletionContentPart[] = [];
      for (const img of pendingAssistantImages) {
        parts.push({
          type: 'image_url' as const,
          image_url: { url: `data:${img.mimeType};base64,${img.data}` },
        });
      }
      const n = pendingAssistantImages.length;
      parts.push({
        type: 'text',
        text: `[The preceding ${n} image(s) are the result(s) generated by AI in the previous response]`,
      });
      if (request.images?.length) {
        for (const img of request.images) {
          parts.push({
            type: 'image_url',
            image_url: { url: `data:${img.mimeType};base64,${img.data}` },
          });
        }
      }
      parts.push({ type: 'text', text: request.prompt });
      messages.push({ role: 'user', content: parts });
      return messages;
    }
  }

  const parts: OpenAI.Chat.Completions.ChatCompletionContentPart[] = [];
  if (request.images?.length) {
    for (const img of request.images) {
      parts.push({
        type: 'image_url',
        image_url: { url: `data:${img.mimeType};base64,${img.data}` },
      });
    }
  }
  parts.push({ type: 'text', text: request.prompt });
  messages.push({ role: 'user', content: parts });

  return messages;
}

async function downloadImage(url: string): Promise<Buffer> {
  console.log(`[OAI] Downloading image from URL: ${url.slice(0, 120)}...`);
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to download image: ${res.status}`);
  return Buffer.from(await res.arrayBuffer());
}

/**
 * Extract images from a content part's image_url.
 * Handles both data-URLs (base64 inline) and regular URLs (download).
 */
async function imageFromUrl(url: string): Promise<AdapterResultImage> {
  const m = url.match(/^data:([^;]+);base64,(.+)$/s);
  if (m) return { data: Buffer.from(m[2], 'base64'), mimeType: m[1] };
  const buf = await downloadImage(url);
  return { data: buf, mimeType: 'image/png' };
}

/**
 * Parse content that can be a string or a multipart array (SDK types).
 */
async function parseContent(
  content: string | Array<{ type: string; text?: string; image_url?: { url: string } }> | null,
): Promise<{ text?: string; images: AdapterResultImage[] }> {
  const images: AdapterResultImage[] = [];
  let text: string | undefined;

  if (typeof content === 'string') {
    text = content;
  } else if (Array.isArray(content)) {
    for (const part of content) {
      if (part.type === 'text' && part.text) {
        text = (text ?? '') + part.text;
      }
      if (part.type === 'image_url' && part.image_url?.url) {
        images.push(await imageFromUrl(part.image_url.url));
      }
    }
  }

  return { text, images };
}

// ─── Non-streaming call ────────────────────────────────

export async function callOpenAI(
  provider: ResolvedProvider,
  request: AdapterRequest,
): Promise<AdapterResponse> {
  const client = createClient(provider);
  const messages = buildMessages(request, provider.imageHistoryStrategy);
  const params = buildParams(provider.advancedSettings);
  const start = Date.now();

  console.log(
    `[OAI] create model=${request.modelId} images=${request.images?.length ?? 0}`,
  );

  try {
    const response = await client.chat.completions.create({
      model: request.modelId,
      messages,
      ...params,
    } as any);

    const elapsedMs = Date.now() - start;
    let text: string | undefined;
    let thinking: string | undefined;
    const images: AdapterResultImage[] = [];

    // Handle image-generation-style `data[]` responses (some proxies)
    const raw = response as any;
    if (raw.data && Array.isArray(raw.data)) {
      for (const item of raw.data) {
        if (item.b64_json) {
          images.push({ data: Buffer.from(item.b64_json, 'base64'), mimeType: 'image/png' });
        } else if (item.url) {
          images.push(await imageFromUrl(item.url));
        }
      }
    }

    if (response.choices?.length) {
      const msg = response.choices[0].message;
      const parsed = await parseContent(msg.content as any);
      if (parsed.text) text = (text ?? '') + parsed.text;
      images.push(...parsed.images);

      if ((msg as any).reasoning_content) {
        thinking = (msg as any).reasoning_content;
      }
    }

    const resolved = await resolveImageUrlsFromText(text);
    if (resolved.images.length > 0) {
      text = resolved.cleanText || undefined;
      images.push(...resolved.images);
    }

    console.log(
      `[OAI] Done: elapsed=${elapsedMs}ms text=${text ? text.length + ' chars' : 'none'} thinking=${thinking ? thinking.length + ' chars' : 'none'} images=${images.length}`,
    );
    return { text, thinking, images, elapsedMs };
  } catch (err: any) {
    const elapsedMs = Date.now() - start;
    const msg = err?.message ?? String(err);
    console.error('[OAI] API error:', msg);
    throw new Error(msg);
  }
}

// ─── Streaming call ────────────────────────────────────

export async function callOpenAIStream(
  provider: ResolvedProvider,
  request: AdapterRequest,
  callbacks: AdapterStreamCallbacks,
): Promise<AdapterResponse> {
  const client = createClient(provider);
  const messages = buildMessages(request, provider.imageHistoryStrategy);
  const params = buildParams(provider.advancedSettings);
  const start = Date.now();

  console.log(`[OAI/Stream] create model=${request.modelId}`);

  let accumulatedText: string | undefined;
  let accumulatedThinking: string | undefined;
  const accumulatedImages: AdapterResultImage[] = [];

  try {
    const stream = await client.chat.completions.create({
      model: request.modelId,
      messages,
      ...params,
      stream: true,
    } as any);

    // NOTE: The SDK handles the case where a proxy returns JSON instead of SSE
    // automatically — it will parse the JSON body and yield a single chunk.

    for await (const chunk of stream as unknown as AsyncIterable<any>) {
      // Handle error objects some proxies embed in chunks
      if (chunk.error) {
        callbacks.onError(chunk.error.message ?? JSON.stringify(chunk.error));
        continue;
      }

      const delta = chunk.choices?.[0]?.delta;
      if (!delta) continue;

      if (typeof delta.reasoning_content === 'string') {
        accumulatedThinking = (accumulatedThinking ?? '') + delta.reasoning_content;
        callbacks.onThinking(delta.reasoning_content);
      }

      if (typeof delta.content === 'string') {
        accumulatedText = (accumulatedText ?? '') + delta.content;
        callbacks.onText(delta.content);
      } else if (Array.isArray(delta.content)) {
        for (const part of delta.content) {
          if (part.type === 'text' && part.text) {
            accumulatedText = (accumulatedText ?? '') + part.text;
            callbacks.onText(part.text);
          }
          if (part.type === 'image_url' && part.image_url?.url) {
            const img = await imageFromUrl(part.image_url.url);
            accumulatedImages.push(img);
            await callbacks.onImage(img);
          }
        }
      }
    }
  } catch (err: any) {
    const msg = err?.message ?? String(err);
    console.error('[OAI/Stream] API error:', msg);
    callbacks.onError(msg);
  }

  const resolved = await resolveImageUrlsFromText(accumulatedText);
  if (resolved.images.length > 0) {
    accumulatedText = resolved.cleanText || undefined;
    for (const img of resolved.images) {
      accumulatedImages.push(img);
      await callbacks.onImage(img);
    }
  }

  const elapsedMs = Date.now() - start;
  console.log(
    `[OAI/Stream] Done: elapsed=${elapsedMs}ms text=${accumulatedText ? accumulatedText.length + ' chars' : 'none'} thinking=${accumulatedThinking ? accumulatedThinking.length + ' chars' : 'none'} images=${accumulatedImages.length}`,
  );

  return { text: accumulatedText, thinking: accumulatedThinking, images: accumulatedImages, elapsedMs };
}
