import OpenAI from 'openai';
import type { AdvancedSettings } from '@ai-retouch/shared';
import { resolveImageUrlsFromText } from './image-url-resolver.js';
import type {
  AdapterRequest,
  AdapterResponse,
  AdapterResultImage,
  AdapterStreamCallbacks,
  ResolvedProvider,
} from './types.js';

// ─── Client ──────────────────────────────────────────────

function createClient(provider: ResolvedProvider): OpenAI {
  const baseURL =
    provider.urlMode === 'full'
      ? provider.baseUrl.replace(/\/+$/, '')
      : `${provider.baseUrl.replace(/\/+$/, '')}/v1`;

  if (provider.useAuthorizationFormat) {
    return new OpenAI({
      baseURL,
      apiKey: 'placeholder',
      defaultHeaders: { 'x-api-key': provider.apiKey },
    });
  }
  return new OpenAI({ baseURL, apiKey: provider.apiKey });
}

// ─── Input types ─────────────────────────────────────────

interface InputText { type: 'input_text'; text: string }
interface InputImage { type: 'input_image'; image_url: string }
interface OutputText { type: 'output_text'; text: string }
type InputContentPart = InputText | InputImage;
type OutputContentPart = OutputText;

interface InputMessage {
  role: 'user' | 'assistant';
  content: InputContentPart[] | OutputContentPart[];
}

// ─── Helpers ─────────────────────────────────────────────

function buildInput(
  request: AdapterRequest,
  strategy: ResolvedProvider['imageHistoryStrategy'],
): string | InputMessage[] {
  const hasHistory = request.history && request.history.length > 0;
  const hasImages = request.images && request.images.length > 0;

  if (!hasHistory && !hasImages) return request.prompt;

  const input: InputMessage[] = [];

  if (hasHistory) {
    let pendingAssistantImages: AdapterRequest['images'] = [];

    for (const turn of request.history!) {
      if (turn.role === 'user') {
        const content: InputContentPart[] = [];

        if (strategy === 'attach_to_user' && pendingAssistantImages.length > 0) {
          for (const img of pendingAssistantImages) {
            content.push({ type: 'input_image', image_url: `data:${img.mimeType};base64,${img.data}` });
          }
          const n = pendingAssistantImages.length;
          content.push({
            type: 'input_text',
            text: `[The preceding ${n} image(s) are the result(s) generated by AI in the previous response]\n\n${turn.content}`,
          });
          pendingAssistantImages = [];
        } else {
          if (turn.images?.length) {
            for (const img of turn.images) {
              content.push({ type: 'input_image', image_url: `data:${img.mimeType};base64,${img.data}` });
            }
          }
          content.push({ type: 'input_text', text: turn.content });
        }

        input.push({ role: 'user', content });
      } else {
        if (turn.images?.length && strategy === 'embed_in_assistant') {
          const content: InputContentPart[] = turn.images.map((img) => ({
            type: 'input_image' as const,
            image_url: `data:${img.mimeType};base64,${img.data}`,
          }));
          content.push({ type: 'output_text' as any, text: turn.content });
          input.push({ role: 'assistant', content: content as any });
        } else {
          if (turn.images?.length) {
            pendingAssistantImages = turn.images;
          }
          input.push({ role: 'assistant', content: [{ type: 'output_text', text: turn.content }] });
        }
      }
    }

    if (strategy === 'attach_to_user' && pendingAssistantImages.length > 0) {
      const content: InputContentPart[] = [];
      for (const img of pendingAssistantImages) {
        content.push({ type: 'input_image', image_url: `data:${img.mimeType};base64,${img.data}` });
      }
      const n = pendingAssistantImages.length;
      content.push({
        type: 'input_text',
        text: `[The preceding ${n} image(s) are the result(s) generated by AI in the previous response]`,
      });
      if (hasImages) {
        for (const img of request.images!) {
          content.push({ type: 'input_image', image_url: `data:${img.mimeType};base64,${img.data}` });
        }
      }
      content.push({ type: 'input_text', text: request.prompt });
      input.push({ role: 'user', content });
      return input;
    }
  }

  const currentContent: InputContentPart[] = [];
  if (hasImages) {
    for (const img of request.images!) {
      currentContent.push({ type: 'input_image', image_url: `data:${img.mimeType};base64,${img.data}` });
    }
  }
  currentContent.push({ type: 'input_text', text: request.prompt });
  input.push({ role: 'user', content: currentContent });

  return input;
}

function buildParams(settings: AdvancedSettings): Record<string, unknown> {
  const params: Record<string, unknown> = {};
  if (settings.temperature?.enabled) params.temperature = settings.temperature.value;
  if (settings.maxOutputTokens?.enabled) params.max_output_tokens = settings.maxOutputTokens.value;
  if (settings.topP?.enabled) params.top_p = settings.topP.value;

  const tk = settings.thinking;
  const reasoning: Record<string, unknown> = {};
  if (tk?.reasoningEffort?.enabled) reasoning.effort = tk.reasoningEffort.value;
  if (tk?.reasoningSummary?.enabled) reasoning.summary = tk.reasoningSummary.value;
  if (Object.keys(reasoning).length > 0) params.reasoning = reasoning;

  return params;
}

function buildTools(request: AdapterRequest): Array<{ type: 'image_generation' }> | undefined {
  if (request.capabilities?.includes('image_generation_tool')) {
    return [{ type: 'image_generation' }];
  }
  return undefined;
}

function parseOutputItems(output: any[]): { text?: string; images: AdapterResultImage[] } {
  let text: string | undefined;
  const images: AdapterResultImage[] = [];

  for (const item of output) {
    if (item.type === 'message') {
      for (const c of item.content ?? []) {
        if (c.type === 'output_text' && c.text) {
          text = (text ?? '') + c.text;
        }
      }
    } else if (item.type === 'image_generation_call' && item.result) {
      images.push({
        data: Buffer.from(item.result, 'base64'),
        mimeType: 'image/png',
      });
    }
  }

  return { text, images };
}

// ─── Non-streaming call ──────────────────────────────────

export async function callOpenAIResponses(
  provider: ResolvedProvider,
  request: AdapterRequest,
): Promise<AdapterResponse> {
  const client = createClient(provider);
  const strategy = provider.imageHistoryStrategy;
  const useNative = strategy === 'native_server_state' && request.previousResponseId;
  const input = useNative ? request.prompt : buildInput(request, strategy);
  const params = buildParams(provider.advancedSettings);
  const tools = buildTools(request);
  const start = Date.now();

  console.log(`[OAI/Responses] create model=${request.modelId} images=${request.images?.length ?? 0} strategy=${strategy} previousResponseId=${request.previousResponseId ?? 'none'}`);

  try {
    const response = await client.responses.create({
      model: request.modelId,
      input: input as any,
      ...(tools ? { tools } : {}),
      ...(useNative ? { previous_response_id: request.previousResponseId } : {}),
      ...params,
    } as any);

    const elapsedMs = Date.now() - start;
    const providerResponseId = (response as any).id as string | undefined;
    let { text, images } = parseOutputItems((response as any).output ?? []);

    const resolved = await resolveImageUrlsFromText(text);
    if (resolved.images.length > 0) {
      text = resolved.cleanText || undefined;
      images.push(...resolved.images);
    }

    console.log(`[OAI/Responses] Done: elapsed=${elapsedMs}ms text=${text ? text.length + ' chars' : 'none'} images=${images.length} responseId=${providerResponseId}`);
    return { text, images, elapsedMs, providerResponseId };
  } catch (err: any) {
    const elapsedMs = Date.now() - start;
    const msg = err?.message ?? String(err);
    console.error('[OAI/Responses] API error:', msg);
    throw new Error(msg);
  }
}

// ─── Streaming call ──────────────────────────────────────

export async function callOpenAIResponsesStream(
  provider: ResolvedProvider,
  request: AdapterRequest,
  callbacks: AdapterStreamCallbacks,
): Promise<AdapterResponse> {
  const client = createClient(provider);
  const strategy = provider.imageHistoryStrategy;
  const useNative = strategy === 'native_server_state' && request.previousResponseId;
  const input = useNative ? request.prompt : buildInput(request, strategy);
  const params = buildParams(provider.advancedSettings);
  const tools = buildTools(request);
  const start = Date.now();

  console.log(`[OAI/Responses/Stream] create model=${request.modelId} strategy=${strategy}`);

  let accumulatedText: string | undefined;
  const accumulatedImages: AdapterResultImage[] = [];
  let providerResponseId: string | undefined;

  try {
    const stream = await client.responses.create({
      model: request.modelId,
      input: input as any,
      ...(tools ? { tools } : {}),
      ...(useNative ? { previous_response_id: request.previousResponseId } : {}),
      ...params,
      stream: true,
    } as any);

    for await (const event of stream as unknown as AsyncIterable<any>) {
      switch (event.type) {
        case 'response.output_text.delta': {
          const delta = event.delta as string | undefined;
          if (delta) {
            accumulatedText = (accumulatedText ?? '') + delta;
            callbacks.onText(delta);
          }
          break;
        }

        case 'response.image_generation_call.partial_image':
          break;

        case 'response.completed': {
          providerResponseId = event.response?.id;
          const output = event.response?.output;
          if (Array.isArray(output)) {
            const parsed = parseOutputItems(output);
            if (parsed.text && !accumulatedText) {
              accumulatedText = parsed.text;
              callbacks.onText(parsed.text);
            }
            for (const img of parsed.images) {
              accumulatedImages.push(img);
              await callbacks.onImage(img);
            }
          }
          break;
        }

        default:
          break;
      }
    }
  } catch (err: any) {
    const msg = err?.message ?? String(err);
    console.error('[OAI/Responses/Stream] API error:', msg);
    callbacks.onError(msg);
  }

  const resolved = await resolveImageUrlsFromText(accumulatedText);
  if (resolved.images.length > 0) {
    accumulatedText = resolved.cleanText || undefined;
    for (const img of resolved.images) {
      accumulatedImages.push(img);
      await callbacks.onImage(img);
    }
  }

  const elapsedMs = Date.now() - start;
  console.log(
    `[OAI/Responses/Stream] Done: elapsed=${elapsedMs}ms text=${accumulatedText ? accumulatedText.length + ' chars' : 'none'} images=${accumulatedImages.length} responseId=${providerResponseId}`,
  );

  return { text: accumulatedText, images: accumulatedImages, elapsedMs, providerResponseId };
}
